wallpaper: boot():/boot/wallpaper.png
wallpaper_style: stretched
term_foreground: ffdddddd
term_background: ff000000

interface_branding_colour: 89b4fa
interface_help_colour: 74c7ec
interface_help_colour_bright: b4befe

/ARTEMIS
    protocol: limine
    path: boot():/boot/artemis
